### ISSUE TITLE
Add escape mechanism

### ISSUE THREAD

**Issue by xxczaki** [xxczaki/light-date#4]
Ideally, it would be an opt-in feature, which would allow writing pattern-reserved sequences (such as `{mm}` or `{EEE}`) without them being formatted. Not all date formatting libraries provide this feature as it's relatively unlikely that one would like to write something like `{mm}`, but it would be nice to have.

We could allow escape through single quotes, like so:

```ts
import {format} from 'light-date';

format(new Date(), `Current date is: {yyyy}/{MM}/{dd} (using '{yyyy}/{MM}/{dd}' format)`);
//                                                            ~~~~~~~~~~~~~~~~
//                                                              the following would not be formatted.
```

Solutions, which I think are worth thinking about:

1. Regular expression change(s)
2. [tagged string template](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), like:
```js
escape`{yyyy}/{MM}/{dd}`
```

**Comment by mtsknn** [comment]
> We could allow escape through single quotes

Hmm, why through single quotes? 🤔 Curious.

What about escaping with backslashes? A minimal implementation would be easy:

- Change the regex from `/{.*?}/g` to `/\\?{.*?}/g`
- Add `if (key[0] === '\\') return key.slice(1);` to the beginning of the replacer function.

Size would grow by 17B for `format()` and by 22B for `localeFormat()`. Performance wouldn't deteriorate, at least not on my machine:

<details><summary>Benchmark results before the change</summary>

```
moment x 693,939 ops/sec ±0.71% (93 runs sampled)
dayjs x 243,503 ops/sec ±0.50% (92 runs sampled)
date-fns format x 338,354 ops/sec ±0.71% (92 runs sampled)
date-fns lightFormat x 437,776 ops/sec ±0.67% (89 runs sampled)
date-format x 799,479 ops/sec ±0.72% (95 runs sampled)
light-date x 1,411,701 ops/sec ±0.52% (95 runs sampled)
Fastest is light-date
┌──────────────────────┬──────────────────────────┬───────────────┬────────────────┐
│ Name                 │ Mean time                │ Ops/sec       │ Diff           │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ moment               │ 0.0000014410480564911898 │ 693,939.384   │ N/A            │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ dayjs                │ 0.000004106732236788547  │ 243,502.606   │ -64.91% faster │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ date-fns format      │ 0.0000029554855182623237 │ 338,353.883   │ 38.95% faster  │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ date-fns lightFormat │ 0.0000022842707522044366 │ 437,776.476   │ 29.38% faster  │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ date-format          │ 0.000001250815211753674  │ 799,478.605   │ 82.62% faster  │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ light-date           │ 7.083652850690489e-7     │ 1,411,701.026 │ 76.58% faster  │
└──────────────────────┴──────────────────────────┴───────────────┴────────────────┘
```

</details>

<details><summary>Benchmark results after the change</summary>

```
moment x 712,358 ops/sec ±0.59% (94 runs sampled)
dayjs x 245,933 ops/sec ±0.48% (95 runs sampled)
date-fns format x 348,883 ops/sec ±0.66% (93 runs sampled)
date-fns lightFormat x 450,877 ops/sec ±0.38% (92 runs sampled)
date-format x 809,482 ops/sec ±0.62% (94 runs sampled)
light-date x 1,412,338 ops/sec ±0.51% (93 runs sampled)
Fastest is light-date
┌──────────────────────┬──────────────────────────┬───────────────┬────────────────┐
│ Name                 │ Mean time                │ Ops/sec       │ Diff           │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ moment               │ 0.0000014037890191278544 │ 712,357.759   │ N/A            │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ dayjs                │ 0.0000040661430722777585 │ 245,933.304   │ -65.48% faster │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ date-fns format      │ 0.0000028662928555488647 │ 348,882.703   │ 41.86% faster  │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ date-fns lightFormat │ 0.0000022178999550658004 │ 450,876.965   │ 29.23% faster  │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ date-format          │ 0.0000012353581175647949 │ 809,481.871   │ 79.53% faster  │
├──────────────────────┼──────────────────────────┼───────────────┼────────────────┤
│ light-date           │ 7.080459677597586e-7     │ 1,412,337.681 │ 74.47% faster  │
└──────────────────────┴──────────────────────────┴───────────────┴────────────────┘
```

</details>

It could be annoying that backslashes would need to be repeated. An alternative would be to use `String.raw`, but that would be rather verbose:

```js
format(new Date(), "Current date is: {yyyy}/{MM}/{dd} (using '\\{yyyy}/\\{MM}/\\{dd}' format)");
format(new Date(), String.raw`Current date is: {yyyy}/{MM}/{dd} (using '\{yyyy}/\{MM}/\{dd}' format)`);
```

**Comment by Rabbitzzc** [comment]
This issue may need to be closed.

**Comment by xxczaki** [comment]
@mtsknn I thought about single quotes because that's how `date-fns` handles it. However, I really like your proposal for using backslashes. Will think about it more and maybe add it soon ;)

**Comment by mtsknn** [comment]
You said that you might add this yourself later, but since it's Hacktoberfest, I went ahead and created #8. 😄 I also created #7. If both PRs are merged, the results would look like this:

|                                            | Size of `format`     | Size of `localeFormat` | Ops/sec (average of 10 runs)
| ------------------------------------------ | :------------------- | :--------------------- | :---------------------------
| **Current**                                | 157 B                | 165 B                  | 1 247 244,9919000003
| **`switch → if` + `key[0] === '\\'`**      | 154 B (- 3)          | 171 B (+ 6)            | 1 201 539,145

It's funny that the size of `format` would even drop with both changes. 😃 And regarding performance, I said this in #7:

> Performance stays about the same – maybe drops a little, but I don't know if 10 runs is enough to tell. In any case, the drop isn't likely too much.

All cases for reference:

|                                            | Size of `format`     | Size of `localeFormat` | Ops/sec (average of 10 runs)
| ------------------------------------------ | :------------------- | :--------------------- | :---------------------------
| **Current**                                | 157 B                | 165 B                  | 1 247 244,9919000003
| **`key[0] === '\\'`**                      | 174 B (+ 17)         | 188 B (+ 23)           | 1 249 209,8028
| **`key.startsWith('\\')`**                 | 180 B (+ 23)         | 193 B (+ 28)           | 1 264 293,1371
| **`switch → if`**                          | 139 B (- 18)         | 154 B (- 11)           | 1 214 782,9195
| **`switch → if` + `key[0] === '\\'`**      | 154 B (- 3)          | 171 B (+ 6)            | 1 201 539,145
| **`switch → if` + `key.startsWith('\\')`** | 158 B (+ 1)          | 176 B (+ 11)           | 1 219 106,8771
